### ISSUE TITLE
Website shut down: http://ffmpeg.arrozcru.org/autobuilds/  Alternatives?

### ISSUE THREAD

**Issue by PhilippBuehler** [yihui/animation#131]
The Website for ffmpeg has been shut down permanently.
http://ffmpeg.arrozcru.org/autobuilds/

Alternatives are:
https://web.archive.org/web/20200916091918mp_/https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.3.1-win64-static.zip

Maybe change the link in the warning when no ffmpeg  is installed?

**Comment by cderv** [comment]
Thanks for the heads up ! 

The link is here
https://github.com/yihui/animation/blob/a6355a1de75fcbf752076bae41e5696b0e7adf61/R/saveVideo.R#L61-L63

I think we should either : change the link to one of those: 

1. Not handle windows case because Windows build are linked from the main website: https://ffmpeg.org/download.html#build-windows
1. Or directly to binary repository (https://github.com/BtbN/FFmpeg-Builds/releases) but you can find the link from the main page. 

I think 1 is enough now

**Comment by cderv** [comment]
Thank you @PhilippBuehler !
