### ISSUE TITLE
avconv to replace ffmpeg?

### ISSUE THREAD

**Issue by yihui** [yihui/animation#26]
<del>ffmpeg has been renamed to libav: http://libav.org</del>

**Comment by skyebend** [comment]
For some time it seemed that Debian and Ubuntu systems simply 'aliased' ffmepg to avconv, so animation library worked with default settings.  At the moment, it seems that this is no longer the case, so saveVideo() fails unless ffmpeg='avconv' argument is given or ffmpeg is build from source.  

```
sh: 1: ffmpeg: not found
Error in system(paste(ffmpeg, "-version"), intern = TRUE) : 
  error in running command
NULL
Warning message:
In saveVideo({ :
  The command "'ffmpeg'" is not available in your system. Please install FFmpeg first: http://ffmpeg.org/download.html
``


Since avconv is provided by default on these systems, maybe animation package should set it as the default if it can't find ffmpeg? like having something in zzz.R like:

```
 if (.Platform$OS.type != "windows")
{
  # check if ffmpeg installed
  if (Sys.which('ffmpeg')==''){
    # can't find ffmpeg, so try avconv
    if(Sys.which('avconv')!=''){
      ani.options(ffmpeg = "avconv")
      message("'ffmpeg' not found on system, using 'avconv' as default instead')
    }
  }
}
```
Does this approach seem feasible to include in animation? Or should I just add it in my dependent library? Or does anyone know more about the ffmpeg/avconv future on these platforms?

**Comment by yulijia** [comment]
Hi, @skyebend 
I made a little change in `saveVideo.R` based on your code, [please see my own repository (branch issue26)](https://github.com/yulijia/animation/blob/issue26/R/saveVideo.R)

Would you mind to help me test if it can works on your Ubuntu or Debain system?

Try install the development version of animation packages on github repository

```
install.packages("devtools")

library(devtools)

dev_mode(on=T)

install_github("animation",username="yulijia",ref="issue26")

library(animation)
saveVideo({
par(mar = c(3, 3, 1, 0.5), mgp = c(2, 0.5, 0), tcl = -0.3, cex.axis = 0.8,
cex.lab = 0.8, cex.main = 1)
ani.options(interval = 0.05, nmax = 300)
brownian.motion(pch = 21, cex = 5, col = "red", bg = "yellow")
}, video.name = "BM.mp4", other.opts = "-b 300k")

# when finished do:
dev_mode(on=F)
```


@yihui 

I didn't delete the "version check" and "if function" in this code hunk, because I do not know if this function supports any other converters.

```
#if saveVideo() only support `ffmpeg` and `avconv` , we can delete some lines
version = try(system(paste(ffmpeg, '-version'), intern = TRUE),silent = TRUE) #  this line can be deleted
if (inherits(version,'try-error')){ #  this line can be deleted
  warning()
} # this line can be deleted

```

**Comment by skyebend** [comment]
Hi Lijia,

Thanks for looking at this!

I found that your patch doesn't work, I think because

when you assign ani.options(ffmpeg = "avconv") on line 52, you asign to 
the global parameter, and its state has already been read on line 45, so 
it is ignored.


I think there is a bit of a question about how this function should work 
wrt preset defaults

I'd think if the user as specifically set ani.oopts ffmpeg, that choise 
should be respected.  And perhaps also if they passed in directly via 
the saveVideo ffmpeg= argument.  (In the CRAN version ani.opts overides 
command argument).


I'd think ideally it might work as follows:


* code in zzz.R  can check if ffmpeg or avconv is available with syswich 
and set ani.options(ffmpeg).  If neither found, leave it null.

* redefine saveVideo() so that its ffmpeg argument ffmpeg = 
ani.options('ffmpeg'),

* inside saveVideo, if ffmpeg argument is null, still try setting it to 
'ffmpeg'

I think this would preserve existing behavior, allow defaulting or user 
specification of either ffmpeg or avconv via either ani.options or the 
saveVideo argument, with the later overriding the former.

Does that make sense?

If not I can try a fork and make a pull request

best,
  -skye

**Comment by yulijia** [comment]
Hi skye ( @skyebend ),

Thanks for your suggestions. 
Pull requests are welcome:)  Let me know if there is anything I can do to help.


Best,
Lijia

**Comment by yulijia** [comment]
Thanks to skye, `saveVideo` function now support *avconv* on linux (Ubuntu and Debian).

I perform to install **ffmpeg** as video converter on  linux. 

Starting with Ubuntu 15.04 "Vivid", FFmpeg's ffmpeg is back in the repositories again.

**Comment by skyebend** [comment]
One question stilil on this, since it now sets a default ani.opts$ffmpeg on linux machines with ffmpeg or avconv installed, should it do so on windows as well? (left a TODO: in the code)

**Comment by yulijia** [comment]
Is there any default installed video converter on Windows ?
I am not familiar with those converters, for me, I do not install any video converter before using `animation` package on Windows. When I need using `saveVideo`, I just need install ffmpeg.

**Comment by skyebend** [comment]
There is not a default converter with Window (that I know of) but I 
think ffmpeg does install to a default location?  At least the example 
for saveVideo() does specify a full path.    I think that if user has 
added ffmpeg to their System Path, the default 'ffmpeg' command will 
work, but if they have installed ffmpeg but not altered their System 
Path, the full path is more likely to work?   I don't normally use 
windows machines so I'm not quite sure.
